FROM flink:1.4.1-hadoop28-alpine
VOLUME /tmp

ADD hbase-site.xml $FLINK_HOME/conf
ADD target/scala-2.11/search-flight-flink-streaming-assembly-0.1.0.jar $FLINK_HOME/libs/search-flight-streaming.jar
RUN sh -c 'touch $FLINK_HOME/libs/search-flight-streaming.jar'

WORKDIR $FLINK_HOME

CMD ["./bin/flink", "run", "-m", "jobmanager.vnet:6123", "-c", "com.mitosis.Main", "./libs/search-flight-streaming.jar", "--port", "9000"]
