FROM openjdk:8-jre
VOLUME /tmp

ENV SPARK_VERSION spark-2.2.1-bin-hadoop2.7
ENV SPARK_HOME /usr/local/spark
ENV PARQUET_HOME $SPARK_HOME/parquet

RUN curl http://apache.mediamirrors.org/spark/spark-2.2.1/$SPARK_VERSION.tgz -o $SPARK_VERSION.tgz; \
    tar xzf $SPARK_VERSION.tgz -C /usr/local/;

RUN cd /usr/local && ln -s $SPARK_VERSION spark

ADD target/scala-2.11/search-flight-streaming-assembly-0.1.0.jar $SPARK_HOME/libs/search-flight-streaming.jar
RUN sh -c 'touch $SPARK_HOME/libs/search-flight-streaming.jar'

WORKDIR $SPARK_HOME

CMD ["bin/spark-submit", "--class", "com.mitosis.Main", "--master", "local[*]", "/usr/local/spark/libs/search-flight-streaming.jar"]
